### ISSUE TITLE
Desktop App

### ISSUE THREAD

**Issue by mayneyao** [mayneyao/eidos#172]
## Some limitations of the web app

- The performance of `sqlite-wasm` has declined and it does not support concurrent read and write operations.
- Currently, `sqlite-wasm` does not support loading extensions or customizing FTS tokenizers, resulting in poor full-text search support for CJK languages.
- `OFPS` and `persistent permissions` have relatively high requirements for browsers, making it difficult for some users to understand and configure them correctly.
- Some features related to LLM have weak support in browsers.
- Web app cannot directly start the API server and needs to rely on other services to forward requests.

## TODO
- [x] electron setup
- [ ] node fs adapter
- [x] native SQLite adapter
- [x] CJK full-text search support
- [ ] extension block/app loader
- [x] built-in API server
- [ ] service worker adapter
- [ ] redesign the right-side panel
- [ ] AI: auto function call
